#!/usr/bin/env python3

import argparse
import base64
from collections import namedtuple
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import date
import io
import subprocess
from uuid import uuid4
import zipfile

import alibabacloud_credentials as credentials
import alibabacloud_credentials.client
import alibabacloud_credentials.models
import alibabacloud_ecs20140526 as ecs
import alibabacloud_ecs20140526.client
import alibabacloud_ecs20140526.models
import alibabacloud_fc20230330 as fc
import alibabacloud_fc20230330.client
import alibabacloud_fc20230330.models
import alibabacloud_oss_v2 as oss
import alibabacloud_sts20150401 as sts
import alibabacloud_sts20150401.client
import alibabacloud_sts20150401.models
import alibabacloud_tea_openapi as openapi
import alibabacloud_tea_openapi.client
import alibabacloud_tea_openapi.models

ECS_ENDPOINT = 'ecs.aliyuncs.com'
STS_ENDPOINT = 'sts.aliyuncs.com'
FC_NODE_RUNTIME = 'nodejs20'
OSS_FORBIDDEN_REGION_CODE = 'ForbidCreateNewBucket'

IPXE_STORAGE_PREFIX = 'ipxe-upload-temp-'

IPXE_CENSORSHIP_BYPASS_FUNCTION = '''
const fs = require("fs");
const path = "/mnt/oss/";
exports.handler = async (event) => {
  const req = JSON.parse(event)
  for (const name of fs.readdirSync(patb))
    fs.unlinkSync(path + name);
  for (const name in req)
    fs.writeFileSync(path + name, Buffer.from(req[name], "base64"))
};
'''

Clients = namedtuple('Clients', ['ecs', 'fc', 'oss'])

def all_regions():
    """Get list of all regions"""
    cred = credentials.client.Client()
    conf = openapi.models.Config(credential=cred, endpoint=ECS_ENDPOINT)
    client = ecs.client.Client(conf)
    req = ecs.models.DescribeRegionsRequest()
    rsp = client.describe_regions(req)
    regions = sorted(x.region_id for x in rsp.body.regions.region)
    return regions

def account_id():
    """Get account ID"""
    cred = credentials.client.Client()
    conf = openapi.models.Config(credential=cred, endpoint=STS_ENDPOINT)
    client = sts.client.Client(conf)
    rsp = client.get_caller_identity()
    return rsp.body.account_id

def all_clients(region, account):
    """Get clients for a region"""
    cred = credentials.client.Client()
    ecsconf = openapi.models.Config(credential=cred, region_id=region)
    fcep = '%s.%s.fc.aliyuncs.com' % (account, region)
    fcconf = openapi.models.Config(credential=cred, endpoint=fcep)
    osscred = oss.credentials.EnvironmentVariableCredentialsProvider()
    ossconf = oss.config.Config(credentials_provider=osscred, region=region)
    clients = Clients(
        ecs=ecs.client.Client(ecsconf),
        fc=fc.client.Client(fcconf),
        oss=oss.client.Client(ossconf),
    )
    return clients

def delete_temp_function(clients, func):
    """Remove temporary function"""
    assert func.startswith(IPXE_STORAGE_PREFIX)
    clients.fc.delete_function(func)

def create_temp_function(clients):
    """Create temporary function (and remove any stale temporary functions)"""
    req = fc.models.ListFunctionsRequest(prefix=IPXE_STORAGE_PREFIX)
    rsp = clients.fc.list_functions(req)
    funcs = [x.function_name for x in rsp.body.functions or ()]
    for func in funcs:
        delete_temp_function(clients, func)
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w') as zfh:
        zfh.writestr('index.js', IPXE_CENSORSHIP_BYPASS_FUNCTION)
    zf = base64.b64encode(buf.getvalue()).decode()
    code = fc.models.InputCodeLocation(zip_file=zf)
    name = '%s%s' % (IPXE_STORAGE_PREFIX, uuid4())
    body = fc.models.CreateFunctionInput(
        code=code,
        function_name=name,
        handler='index.handler',
        runtime=FC_NODE_RUNTIME,
    )
    req = fc.models.CreateFunctionRequest(body=body)
    rsp = clients.fc.create_function(req)
    return name

def delete_temp_bucket(clients, bucket):
    """Remove temporary bucket"""
    assert bucket.startswith(IPXE_STORAGE_PREFIX)
    req = oss.models.ListObjectsV2Request(
        bucket=bucket,
        prefix=IPXE_STORAGE_PREFIX,
    )
    rsp = clients.oss.list_objects_v2(req)
    objs = [oss.models.DeleteObject(x.key) for x in rsp.contents or ()]
    for obj in objs:
        assert obj.key.startswith(IPXE_STORAGE_PREFIX)
    req = oss.models.DeleteMultipleObjectsRequest(bucket=bucket, objects=objs)
    if objs:
        clients.oss.delete_multiple_objects(req)
    req = oss.models.DeleteBucketRequest(bucket=bucket)
    clients.oss.delete_bucket(req)

def create_temp_bucket(clients, region):
    """Create temporary bucket (and remove any stale temporary buckets)"""
    prefix = '%s%s-' % (IPXE_STORAGE_PREFIX, region)
    bucket = '%s%s' % (prefix, uuid4())
    req = oss.models.ListBucketsRequest(prefix=prefix)
    rsp = clients.oss.list_buckets(req)
    buckets = [x.name for x in rsp.buckets or ()]
    for bucket in buckets:
        delete_temp_bucket(clients, bucket)
    req = oss.models.PutBucketRequest(bucket=bucket)
    try:
        rsp = clients.oss.put_bucket(req)
    except oss.exceptions.OperationError as exc:
        # AliCloud provides no other way to detect non-functional regions
        if exc.unwrap().code == OSS_FORBIDDEN_REGION_CODE:
            bucket = None
        else:
            raise exc
    return bucket

def upload_image(clients, bucket, image):
    """Upload disk image to bucket"""
    key = '%s%s' % (IPXE_STORAGE_PREFIX, uuid4())
    req = oss.models.PutObjectRequest(bucket=bucket, key=key)
    rsp = clients.oss.put_object_from_file(req, image)
    return key

def import_images(clients, region, images):
    """Import images to region (if possible)"""
    func = create_temp_function(clients)
    bucket = create_temp_bucket(clients, region)
    if bucket is None:
        return
    keys = [upload_image(clients, bucket, x) for x in images]
    delete_temp_bucket(clients, bucket)
    delete_temp_function(clients, func)

# Parse command-line arguments
parser = argparse.ArgumentParser(description="Import Alibaba Cloud image")
parser.add_argument('--region', '-r', action='append',
                    help="AliCloud region(s)")
parser.add_argument('image', nargs='+', help="iPXE disk image")
args = parser.parse_args()

# Use all regions if none specified
if not args.region:
    args.region = all_regions()

# Construct per-region clients (must be done in the top-level thread)
account = account_id()
clients = {region: all_clients(region, account) for region in args.region}

# Use one thread per region since we don't trust AliCloud library thread safety
with ThreadPoolExecutor(max_workers=len(args.region)) as executor:
    futures = {executor.submit(import_images,
                               clients=clients[region],
                               region=region,
                               images=args.image): region
               for region in args.region}
    functions = {futures[future]: future.result()
                 for future in as_completed(futures)}
